mastersetup revisions

diff --git a/mastersetup b/mastersetup
--- a/mastersetup
+++ b/mastersetup
@@ -3,7 +3,7 @@
 #################################################################################
 # Enabling Raspberry Pi to run SmartThings direct-connected device applications
 #                Master setup and configure bash script
-#                           Version 0.20210401
+#                           Version 0.20210406
 #
 # Copyright 2020 Todd A. Austin
 #
@@ -114,7 +114,7 @@ getyesno() {
   read -rsn1 keyin
  done
 
- echo
+ echo -e "$keyin\n"
  keyresp=$keyin
 
 }
@@ -154,7 +154,7 @@ getjsonitem() {
   else
     return 1
   fi
-    
+
 }
 
 # Execute git clone for given package URL
@@ -162,28 +162,36 @@ clonepkg() {
 
   step=$1
   URL=$2
+  
+  savIFS=$IFS
+  IFS='/'
+  read -a path <<< "$URL"
+
+  IFS='.'
+  read -a dname <<< "${path[4]}"
+  IFS=$savIFS
+  PKGDIR=$HOME/${dname[0]}
 
   cd "$HOME"
   output=$(git clone "$URL" 2>&1)
   errnum=$?
-  cd "$rpipkgdir"
-  
+
   if [ $errnum -eq 0 ]
     then
-      
+
       # Confirm that the respository directory now exists
 
-      savIFS=$IFS
-      IFS='/'
-      read -a path <<< "$URL"
-
-      IFS='.'
-      read -a dname <<< "${path[4]}"
-      IFS=$savIFS
-
-      if [ -d $HOME/${dname[0]} ]; then
+      if [ -d $PKGDIR ]; then
         echo -e "\n\t\e[92mInstallation successful\e[0m\n"
         stepst[step]=$done
+        
+        if [ $step -eq 0 ]; then
+          cd $PKGDIR
+          echo -e "\n\n\e[96mPLEASE RESTART mastersetup NOW (./mastersetup)\e[0m\n"
+          updatestatfile
+          exit 0
+        fi
+        
       else
         echo -e "\n\t\e[91mSomething went wrong: path to package not found\e[0m\n"
       fi
@@ -191,8 +199,39 @@ clonepkg() {
     else
       if [[ "$output" == *"already exists"* ]]
         then
-          echo -e "\t\e[0m  >> It looks like the package is already installed\n"
           stepst[step]=$done
+        
+          echo -e "\t\e[0m  >> It looks like the package is already installed\n"
+          echo -en "\t\e[96m  >> Do you want to pull the latest available files? (y/n): \e[0m"
+          getyesno
+          echo
+
+          if [ $keyresp == "y" ]; then
+
+            cd $PKGDIR
+            
+            if [[ "$URL" =~ "st-device-sdk-c" ]]; then
+              output=$(git pull origin master)
+            else
+              output=$(git pull origin main)
+            fi
+            
+            echo $output
+            errnum=$?
+
+            if [ $errnum -eq 0 ]; then
+              if [ $step -eq 0 ]; then
+              
+                if [[ "$output" =~ "mastersetup" ]]; then
+                  echo -e "\n\n\e[96mPLEASE RESTART mastersetup NOW (./mastersetup)\e[0m\n"
+                  exit 0
+                fi
+              fi
+            else
+              echo -e "\n\t\e[91mgit reported error number: $errnum\n"
+            fi
+          fi
+
         else
           echo -e "\n\t\e[91mgit reported error number: $errnum\n"
           echo -e "\t$output\e[0m\n"
@@ -328,7 +367,7 @@ step2() {
 
   bash $rpipkgdir/installSDKdeps
 
-  echo -ne "\n\n\t\e[95mDid you encounter any errors or additional dependencies? (\e[1my/n\e[22m)"
+  echo -ne "\n\n\t\e[95mDid you encounter any errors or additional dependencies? (\e[1my/n\e[0m) "
   getyesno
 
   if [ $keyresp == "y" ]
@@ -506,8 +545,7 @@ step6() {
   
   if [ $errnum == 0 ]; then
   
-    echo -en "\n\t\e[93mNote: Deprecated warnings are normal!\e[0m"
-    echo -en "\n\t\e[95mDid you see any errors (\e[1my/n\e[22m)? \e[0m"
+    echo -en "\n\t\e[95mDid you have any errors (\e[1my/n\e[22m)? \e[0m"
     getyesno
     
     if [ "$keyresp" == "n" ]; then
@@ -557,11 +595,9 @@ step7() {
 # Onboard the example device
 step8() {
   
-  echo -e "\n\t\e[97mPrepare to onboard your device\e[0m"
-  echo -e "\n\tOpen the SmartThings mobile app and begin the add-device"
-  echo -e "\tprocess for your test device."
-  echo -e "\n\t\e[95mPress any key when you've found your Developer Mode"
-  echo -en "\ttest device and are ready to proceed "
+  echo -e "\n\t\e[97mPrepare to onboard your device!\e[0m"
+  echo -e "\n\tOpen the SmartThings mobile app and begin the 'Add Device' process"
+  echo -en "\n\t\e[95mPress any key once you have tapped 'Scan QR code'"
   read -rsn1 keyin
   echo 
   
